(ns ruuvi-server.database.entities
  (:use korma.db)
  (:use korma.core)
  (:use [clojure.tools.logging :only (debug info warn error)])
  (:import org.joda.time.DateTime)
  )

(defn init-entities
  "Map entities and add them to ruuvi-server.models.entities namespace"
  []
  (in-ns 'ruuvi-server.database.entities)
  (info "Mapping entities")
  
  (defentity tracker
    (table :trackers)
    (pk :id)
    (entity-fields :id :tracker_code :name :latest_activity :shared_secret)
    )
  
  (defentity event-extension-type
    (table :event_extension_types)
    (pk :id)
    (entity-fields :name :description)
    )
  
  (defentity event-extension-value
    (table :event_extension_values)
    (pk :id)
    (entity-fields :value)
    (belongs-to event-extension-type {:fk :event_extension_type_id})
    )
  
  (defentity event-location
    (table :event_locations)
    (pk :id)
    (entity-fields :latitude :longitude)
    )
  
  (defentity event
    (table :events)
    (pk :id)
    (entity-fields :event_time :created_on)
    (belongs-to tracker {:fk :tracker_id})
    (has-many event-location {:fk :event_id})
    (has-many event-extension-value {:fk :event_id})
    )

  ;; private functions
  (defn- to-sql-timestamp [date]
    (if date
      (java.sql.Timestamp. (.getMillis date))
      nil))
  
  (defn- current-sql-timestamp []
    (to-sql-timestamp (org.joda.time.DateTime)))
  
  (defn- remove-nil-values [map-data]
    (flatten (filter (fn [x] (nth x 1) ) map-data) ))
  
  ;; public functions
  (defn get-event [event_id]
    (first (select event
                   (with tracker)
                   (with event-location)
                   (with event-extension-value)
                   (where {:id event_id})))
    )
  
  (defn search-events 
    "Search events: criteria is a map that can contain following keys.
- :createTimeStart <DateTime>, find events that are created (stored) to database later than given time (inclusive).
- :eventTimeStart <DateTime>, find events that are created in tracker later than given time (inclusive).
TODO supports only the eventTimeStart
TODO calculates milliseconds wrong (12:30:01.000 is rounded to 12:30:01 but 12:30:01.001 is rounded to 12:30:02)
"
    [criteria]
 
    (let [event-start (:eventTimeStart criteria)
          create-start (:createTimeStart criteria)
          conditions (merge (when event-start {:event_time [>= (to-sql-timestamp event-start)]})
                            (when create-start {:created_on [>= (to-sql-timestamp create-start)]})
                            )]
      (if (not (empty? conditions))
        (select event
                (with event-location)
                (with event-extension-value)
                (where (and {:event_time [>= (to-sql-timestamp event-start)] }))
                )
        '())))
  
  (defn get-events [ids]
    (select event
            (with event-location)
            (with event-extension-value)
            (where (in :id ids))))
  
  (defn get-all-events []
    (select event
            (with event-location)
            (with event-extension-value)
            ))
  
  (defn get-all-trackers []
    (select tracker)
    )
  
  (defn get-tracker [id]
    ;; TODO support also fetching with tracker_indentifier
    (first (select tracker
                   (where {:id id}))))
  
  (defn get-trackers [ids]
    (select tracker
            (where (in :id ids))))
  
  (defn get-tracker-by-code [tracker-code]
    (first (select tracker
                   (where {:tracker_code tracker-code}))))
  
  (defn get-tracker-by-code! [tracker-code & tracker-name]
    (let [existing-tracker (get-tracker-by-code tracker-code)]
      (if existing-tracker
        existing-tracker
        (insert tracker (values {:tracker_code tracker-code
                                 :name (or tracker-name tracker-code)}))
        )))

  (defn get-extension-type-by-name [type-name]
    (first (select event-extension-type
                   (where {:name (str (name type-name))}))))
  
  (defn get-extension-type-by-name! [type-name]
    (let [existing-extension-type (get-extension-type-by-name type-name)]
      (if existing-extension-type
        existing-extension-type
        (insert event-extension-type (values {:name (str (name type-name))
                                              :description "Autogenerated"}))
        )))
  
  (defn- update-tracker-latest-activity [id]
    (update tracker
            (set-fields {:latest_activity (java.sql.Timestamp. (System/currentTimeMillis)) })
            (where {:id id})))
  
  (defn create-tracker [code name shared-secret]
    (info "Create new tracker" name "(" code ")")
    (insert tracker (values
                     {:tracker_code code
                      :shared_secret shared-secret
                      :name name})))
  
  (defn create-event [data]
    (let [extension-keys (filter (fn [key]
                                 (.startsWith (str (name key)) "X-"))
                                 (keys data))
          tracker (get-tracker-by-code! (:tracker_code data))
          latitude (:latitude data)
          longitude (:longitude data)
          
          event-entity (insert event (values
                                      {:tracker_id (tracker :id)
                                       :event_time (or (to-sql-timestamp (:event_time data))
                                                       (current-sql-timestamp) )
                                       }))]
      
      (if (and latitude longitude)
        (insert event-location (values
                                {:event_id (:id event-entity)
                                 :latitude latitude
                                 :longitude longitude
                                 :accuracy (:accuracy data)
                                 :satellite_count (:satellite_count data)
                                 :altitude (:altitude data)}))
        )
    
      (doseq [key extension-keys]
        (insert event-extension-value
                (values
                 {:event_id (:id event-entity)
                  :value (data key)
                  :event_extension_type_id (:id (get-extension-type-by-name! key))
                  }
                 )))
      (update-tracker-latest-activity (tracker :id))
      event-entity
      ))

  )